/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.itpm_timetable_management;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gayath
 */
public class AddNotAvailableTime extends javax.swing.JFrame {
    static final String DB_URL = "jdbc:mysql://remotemysql.com:3306/QoQsk4BeEJ";
    static final String username = "QoQsk4BeEJ";
    static final String password = "r7p32rsm8e";
    /**
     * Creates new form AddNotAvailableTime
     */
    public AddNotAvailableTime(){
        initComponents();
        
    }
    
    Connection conn;
    private void showDetails() throws SQLException, ClassNotFoundException{
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection(DB_URL, username, password);
        String grp = (String)jComboBox1.getSelectedItem();
        if("Lecturer".equals(grp)){
            
              System.out.println("l");
        Statement statement = conn.createStatement();
        String query = "SELECT Lecturer_name from lecturers";
        ResultSet rs = statement.executeQuery(query);
       
       while(rs.next()){
             
         jComboBox2.addItem(rs.getString("Lecturer_name"));
             
       
       }
       conn.close();
       }else if("Session".equals(grp)){
       System.out.println("s");
       Statement stmt = null;
       ResultSet rs = conn.createStatement().executeQuery("SELECT subcode,tags,groups from session"); 
       
       while(rs.next()){
             
         jComboBox2.addItem(rs.getString("subcode")+"/"+rs.getString("tags")+"/"+rs.getString("groups"));
           
       }
           conn.close();
       }else if("Group".equals(grp)){
           System.out.println("g");
       Statement stmt = null;
       ResultSet rs = conn.createStatement().executeQuery("SELECT id from groupids"); 
       
       while(rs.next()){
             
         jComboBox2.addItem(rs.getString("id"));
           
       }
       conn.close();
       }else if("Sub-group".equals(grp)){
           System.out.println("sub");
        Statement stmt = null;
       ResultSet rs = conn.createStatement().executeQuery("SELECT id from subgroupids");

       while(rs.next()){
             
         jComboBox2.addItem(rs.getString("id"));
           
       }
       conn.close();
       }
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Nexa Bold", 0, 36)); // NOI18N
        jLabel1.setText("Add Not Available Times");

        jLabel2.setFont(new java.awt.Font("Nexa Bold", 0, 24)); // NOI18N
        jLabel2.setText("Select Type");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Lecturer", "Session", "Group", "Sub-group" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Nexa Bold", 0, 24)); // NOI18N
        jLabel3.setText("Select ID");

        jComboBox2.setSelectedIndex(-1);

        jLabel4.setFont(new java.awt.Font("Nexa Bold", 0, 24)); // NOI18N
        jLabel4.setText("Select Day");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        jLabel5.setFont(new java.awt.Font("Nexa Bold", 0, 24)); // NOI18N
        jLabel5.setText("Select Start Time");

        jSpinner1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jSpinner2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));

        jLabel6.setFont(new java.awt.Font("Nexa Bold", 0, 24)); // NOI18N
        jLabel6.setText("Select End Time");

        jSpinner3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jSpinner4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));

        jButton1.setFont(new java.awt.Font("Nexa Bold", 0, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(339, 339, 339))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String day = (String) jComboBox3.getSelectedItem();
        String type = (String) jComboBox1.getSelectedItem();
        int sHour = (int) jSpinner1.getValue();
        int eHour = (int) jSpinner3.getValue();
        int sMin  = (int) jSpinner2.getValue();
        int eMin  = (int) jSpinner4.getValue();
        String ampm = (String) jComboBox4.getSelectedItem();
        String ampm1 = (String) jComboBox5.getSelectedItem();
        String startTime = "";
        String endTime = "";
        String id = (String) jComboBox2.getSelectedItem();

        if(jComboBox1.equals("") ||day.equals("") || sHour == 0 || eHour == 0  ){

            JOptionPane.showMessageDialog(this,"Please Select Required Information","Error",JOptionPane.ERROR_MESSAGE);
           
        }
        else{

            try {
                if(ampm.equals("PM")){
                    
                    if(sHour == 1){
                        sHour = 13;
                    }else if(sHour == 2){
                        
                        sHour = 14;
                    }else if(sHour == 3){
                        
                        sHour = 15;
                    }else if(sHour == 4){
                        
                        sHour = 16;
                    }else if(sHour == 5){
                        
                        sHour = 17;
                    }else if(sHour == 6){
                        
                        sHour = 18;
                    }else if(sHour == 7){
                        
                        sHour = 19;
                    }else if(sHour == 8){
                        
                        sHour = 20;
                    }else if(sHour == 9){
                        
                        sHour = 21;
                    }else if(sHour == 10){
                        
                        sHour = 22;
                    }else if(sHour == 11){
                        
                        sHour = 23;
                    }
                    
                }else if(ampm.equals("AM") && sHour == 12){
                    sHour = 00;
                }
                //------------------------------------------------------------------------------------------
                if(ampm1.equals("PM")){
                    
                    if(eHour == 1){
                        eHour = 13;
                    }else if(eHour == 2){
                        
                        eHour = 14;
                    }else if(eHour == 3){
                        
                        eHour = 15;
                    }else if(eHour == 4){
                        
                        eHour = 16;
                    }else if(eHour == 5){
                        
                        eHour = 17;
                    }else if(eHour == 6){
                        
                        eHour = 18;
                    }else if(eHour == 7){
                        
                        eHour = 19;
                    }else if(eHour == 8){
                        
                        eHour = 20;
                    }else if(eHour == 9){
                        
                        eHour = 21;
                    }else if(eHour == 10){
                        
                        eHour = 22;
                    }else if(eHour == 11){
                        
                        eHour = 23;
                    }
                    
                }else if(ampm1.equals("AM") && eHour == 12){
                    eHour = 00;
                }
                
                
                //----------------------------------------------------------------------------------
                if(sHour > eHour){
                    
                 jSpinner1.setValue(0);
                 jSpinner3.setValue(0);
                 jSpinner2.setValue(0);
                 jSpinner4.setValue(0);
                 throw new ArithmeticException("exception");
                
                }else if(sHour == eHour && sMin > eMin){
                
                 jSpinner1.setValue(0);
                 jSpinner3.setValue(0);
                 jSpinner2.setValue(0);
                 jSpinner4.setValue(0);
                 throw new ArithmeticException("exception");
                
                }
                
                
                //----------------------------------------------------------------------------------
                
                
                
                
                startTime = sHour+":"+sMin+":00";
                endTime = eHour+":"+eMin+":00";
                String grp = (String)jComboBox1.getSelectedItem();
                if("Session".equals(grp)){
                    
                    
                    try {
                        String[] sessionArray = id.split("/",3);
                        
                        
                        
                        Statement stmt = null;
                        Class.forName("com.mysql.jdbc.Driver");
       conn = DriverManager.getConnection(DB_URL, username, password);
       ResultSet rs = conn.createStatement().executeQuery("SELECT id from session where subcode = '"+sessionArray[0]+"' and tags = '"+sessionArray[1]+"' and groups = '"+sessionArray[2]+"'"); 
                        
                        while(rs.next()){
                            
                            id = rs.getString("id");
                            
                            
                            
                        }      
                    conn.close();
                    } catch (Exception ex) {
                            Logger.getLogger(AddNotAvailableTime.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    
                }
                
                
                
                String uniqueID = UUID.randomUUID().toString();
                
               Class.forName("com.mysql.jdbc.Driver");
               conn = DriverManager.getConnection(DB_URL, username, password);
               conn.createStatement().executeUpdate("INSERT INTO NotAvailableTime(type,typeId,Day,startTime,endTime)  "
                        +" VALUES ("
                        +"'"+type+"' ,"
                        +"'"+id+"' ,"
                         +"'"+day+"' ,"
                         +"'"+startTime+"' ,"
                         +"'"+endTime+"' )"); 
               
                       
                
                
                
                conn.close();
                
                //succes msg
                JOptionPane.showMessageDialog(this," Details added succesfully","Succesful",JOptionPane.INFORMATION_MESSAGE);
                
            } catch (SQLException ex) {
                Logger.getLogger(AddNotAvailableTime.class.getName()).log(Level.SEVERE, null, ex);
               
            }catch (ArithmeticException ex) {
               JOptionPane.showMessageDialog(this, "Start time should be less than end time","Error",JOptionPane.ERROR_MESSAGE);
               
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddNotAvailableTime.class.getName()).log(Level.SEVERE, null, ex);
            }
          
    }                               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jComboBox2.removeAllItems();
        try {
            showDetails();
        } catch (SQLException ex) {
            Logger.getLogger(AddNotAvailableTime.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddNotAvailableTime.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNotAvailableTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNotAvailableTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNotAvailableTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNotAvailableTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNotAvailableTime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    // End of variables declaration//GEN-END:variables
}
